const KEY="personalForecastDashboard.v1";
const DEFAULTS={currencySymbol:"$",currentSavings:0,savingPerPay:0,tripTarget:0,payFrequency:"fortnightly",nextPayDate:"",vacationStart:"2026-08-14",vacationEnd:"2026-10-31",leaveBalanceHours:0,leaveAccrualPerPay:0,hoursPerWorkDay:7.6,plannedLeaveHours:"",oneOffItems:[]};
let data=loadData();
const $=id=>document.getElementById(id);
const fields=["currencySymbol","currentSavings","savingPerPay","tripTarget","payFrequency","nextPayDate","vacationStart","vacationEnd","leaveBalanceHours","leaveAccrualPerPay","hoursPerWorkDay","plannedLeaveHours"];

document.addEventListener("DOMContentLoaded",()=>{bind();hydrate();render();if("serviceWorker" in navigator){navigator.serviceWorker.register("./sw.js").catch(()=>{});}});

function bind(){
  $("toggleSettingsBtn").addEventListener("click",()=>$("settingsPanel").classList.toggle("hidden"));
  fields.forEach(id=>$(id).addEventListener("input",()=>{saveFields();render();}));
  $("oneOffForm").addEventListener("submit",addItem);
  $("exportBtn").addEventListener("click",exportBackup);
  $("importInput").addEventListener("change",importBackup);
  $("resetBtn").addEventListener("click",()=>{if(confirm("Reset all dashboard data saved in this browser?")){data={...DEFAULTS,oneOffItems:[]};persist();hydrate();render();}});
}

function loadData(){try{const saved=JSON.parse(localStorage.getItem(KEY));return saved&&typeof saved==="object"?{...DEFAULTS,...saved,oneOffItems:Array.isArray(saved.oneOffItems)?saved.oneOffItems:[]}:{...DEFAULTS,oneOffItems:[]};}catch{return {...DEFAULTS,oneOffItems:[]};}}
function persist(){localStorage.setItem(KEY,JSON.stringify(data));}
function hydrate(){fields.forEach(id=>$(id).value=data[id]??"");}
function saveFields(){fields.forEach(id=>{const input=$(id);data[id]=input.type==="number"?(input.value===""?"":Number(input.value)):input.value;});persist();}
function num(value){const n=Number(value);return Number.isFinite(n)?n:0;}
function start(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate());}
function parseDate(value){if(!value)return null;const p=String(value).split("-").map(Number);if(p.length!==3||p.some(Number.isNaN))return null;return start(new Date(p[0],p[1]-1,p[2]));}
function fmtDate(date){return date?new Intl.DateTimeFormat("en-AU",{day:"2-digit",month:"short",year:"numeric"}).format(date):"Not set";}
function fmtNum(value,digits=1){return new Intl.NumberFormat("en-AU",{maximumFractionDigits:digits}).format(num(value));}
function money(value){return `${data.currencySymbol||"$"}${new Intl.NumberFormat("en-AU",{maximumFractionDigits:0}).format(num(value))}`;}
function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}

function addCycle(date){const d=new Date(date);if(data.payFrequency==="weekly"){d.setDate(d.getDate()+7);return d;}if(data.payFrequency==="monthly"){const day=d.getDate();d.setMonth(d.getMonth()+1);if(d.getDate()<day)d.setDate(0);return d;}d.setDate(d.getDate()+14);return d;}
function paydaysUntil(target,today=start(new Date())){const next=parseDate(data.nextPayDate);if(!next||!target)return[];let d=start(next),guard=0;while(d<today&&guard<600){d=addCycle(d);guard++;}const out=[];guard=0;while(d<=target&&guard<600){out.push(new Date(d));d=addCycle(d);guard++;}return out;}
function itemTotalUntil(target,today=start(new Date())){return data.oneOffItems.reduce((total,item)=>{const d=parseDate(item.date);if(!d||d<today||d>target)return total;return total+(item.type==="income"?num(item.amount):-num(item.amount));},0);}
function forecast(target,today=start(new Date())){if(!target)return num(data.currentSavings);return num(data.currentSavings)+num(data.savingPerPay)*paydaysUntil(target,today).length+itemTotalUntil(target,today);}
function weekdaysInclusive(a,b){let count=0,d=new Date(a);while(d<=b){const day=d.getDay();if(day!==0&&day!==6)count++;d.setDate(d.getDate()+1);}return count;}
function leaveRequired(startDate,endDate){if(data.plannedLeaveHours!==""&&data.plannedLeaveHours!==null&&Number(data.plannedLeaveHours)>=0)return num(data.plannedLeaveHours);if(!startDate||!endDate||endDate<startDate)return 0;return weekdaysInclusive(startDate,endDate)*num(data.hoursPerWorkDay||7.6);}

function render(){const today=start(new Date()),vac=parseDate(data.vacationStart),end=parseDate(data.vacationEnd),yearEnd=new Date(today.getFullYear(),11,31);const pdVac=paydaysUntil(vac,today);$("todayLine").textContent=`Today: ${fmtDate(today)}`;$("savingsVacation").textContent=money(forecast(vac,today));$("savingsVacationMeta").textContent=vac?`Estimated on ${fmtDate(vac)}`:"Set a vacation start date.";$("savingsYearEnd").textContent=money(forecast(yearEnd,today));$("savingsYearEndMeta").textContent=`Estimated on ${fmtDate(yearEnd)}`;$("paydaysLeft").textContent=pdVac.length;$("paydaysLeftMeta").textContent=vac?`${data.payFrequency} cycle until ${fmtDate(vac)}`:"Set a vacation start date.";renderCountdown(today,vac,end);renderLeave(vac,end,pdVac.length);renderTarget(forecast(vac,today));renderUpcoming(today,vac);renderPaydayTable(today,vac);renderItemsTable();}
function renderCountdown(today,vac,end){if(!vac){$("tripCountdown").textContent="Set date";$("tripCountdownMeta").textContent="Set a start date.";return;}const days=Math.max(0,Math.ceil((vac-today)/86400000));$("tripCountdown").textContent=`${days} days`;$("tripCountdownMeta").textContent=`${fmtNum(days/7)} weeks / ${fmtNum(days/14)} fortnights. Trip ends ${fmtDate(end)}.`;}
function renderLeave(vac,end,paydays){const available=num(data.leaveBalanceHours)+num(data.leaveAccrualPerPay)*paydays;const required=leaveRequired(vac,end);const gap=available-required;$("leaveByVacation").textContent=`${fmtNum(available)} hrs`;$("leaveByVacationMeta").textContent=`${fmtNum(num(data.leaveBalanceHours))} current + ${fmtNum(num(data.leaveAccrualPerPay))} hrs per pay.`;$("leaveGap").textContent=`${gap>=0?"+":""}${fmtNum(gap)} hrs`;$("leaveGap").className=gap>=0?"good":"bad";$("leaveGapMeta").textContent=`Estimated leave needed: ${fmtNum(required)} hrs.`;}
function renderTarget(balance){const target=num(data.tripTarget);if(target<=0){$("targetBadge").textContent="No target set";$("targetProgress").style.width="0%";$("targetProgressText").textContent="Set a trip savings target to track readiness.";return;}const pct=Math.min(100,Math.max(0,balance/target*100)),gap=balance-target;$("targetBadge").textContent=`${fmtNum(pct)}%`;$("targetProgress").style.width=`${pct}%`;$("targetProgressText").textContent=gap>=0?`Projected to be ${money(gap)} above target by vacation.`:`Projected shortfall: ${money(Math.abs(gap))} by vacation.`;}
function renderUpcoming(today,vac){const list=$("upcomingItems");list.innerHTML="";const items=data.oneOffItems.filter(item=>{const d=parseDate(item.date);return d&&d>=today&&(!vac||d<=vac);}).sort((a,b)=>parseDate(a.date)-parseDate(b.date)).slice(0,6);if(!items.length){list.innerHTML='<li><span class="muted">No one-off items before vacation.</span></li>';return;}items.forEach(item=>{const li=document.createElement("li"),sign=item.type==="income"?"+":"-";li.innerHTML=`<span><strong>${escapeHtml(item.name)}</strong><br><span class="muted">${fmtDate(parseDate(item.date))}</span></span><span class="${item.type==="income"?"good":"bad"}">${sign}${money(item.amount)}</span>`;list.appendChild(li);});}
function renderPaydayTable(today,vac){const body=$("paydayTable");body.innerHTML="";const dates=paydaysUntil(vac,today).slice(0,10);if(!data.nextPayDate||!dates.length){body.innerHTML='<tr><td colspan="3" class="muted">Set your next payday and vacation start date to generate a payday timeline.</td></tr>';return;}dates.forEach((date,i)=>{const row=document.createElement("tr");row.innerHTML=`<td>${fmtDate(date)}</td><td>${money(forecast(date,today))}</td><td>${i===0?"Next expected payday":""}</td>`;body.appendChild(row);});}
function renderItemsTable(){const body=$("itemsTable");body.innerHTML="";if(!data.oneOffItems.length){body.innerHTML='<tr><td colspan="5" class="muted">No one-off items added.</td></tr>';return;}data.oneOffItems.slice().sort((a,b)=>parseDate(a.date)-parseDate(b.date)).forEach(item=>{const row=document.createElement("tr");row.innerHTML=`<td>${escapeHtml(item.name)}</td><td>${item.type}</td><td>${money(item.amount)}</td><td>${fmtDate(parseDate(item.date))}</td><td><button class="secondary" type="button" data-remove="${item.id}">Remove</button></td>`;body.appendChild(row);});body.querySelectorAll("[data-remove]").forEach(btn=>btn.addEventListener("click",()=>{data.oneOffItems=data.oneOffItems.filter(item=>item.id!==btn.dataset.remove);persist();render();}));}
function addItem(event){event.preventDefault();const name=$("itemName").value.trim(),type=$("itemType").value,amount=Number($("itemAmount").value),date=$("itemDate").value;if(!name||!date||!Number.isFinite(amount)||amount<=0){alert("Add a name, amount, and date.");return;}data.oneOffItems.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name,type,amount,date});persist();$("oneOffForm").reset();render();}
function exportBackup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`forecast-dashboard-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function importBackup(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);data={...DEFAULTS,...imported,oneOffItems:Array.isArray(imported.oneOffItems)?imported.oneOffItems:[]};persist();hydrate();render();alert("Backup imported.");}catch{alert("Could not import this backup file.");}finally{event.target.value="";}};reader.readAsText(file);}
